{
 "title": "Flink Dashboard",
 "time": { "from": "now-5m", "to": "now-1s" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Task Manager CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Manager CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Manager Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Manager Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "flink_taskmanager_System_Network_eno1_SendRate",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}