{
 "title": "Kafka Services",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "WordCountOut", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{topic=\"WordCountOut\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalproducerequests_total{topic=\"WordCountOut\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{topic=\"WordCountOut\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kafka_log_log_size{topic=\"WordCountOut\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Start Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{topic=\"WordCountOut\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log End Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{topic=\"WordCountOut\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WordCountIn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalfetchrequests_total{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalproducerequests_total{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "kafka_log_log_size{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_committedOffset{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Start Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log End Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{topic=\"WordCountIn\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}