{
 "title": "Storm Services",
 "time": { "from": "now-5m", "to": "now-1s" },
 "refresh": "1s",
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\"}[2s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 - 100 * (sum(node_memory_MemFree_bytes{job=\"node_exporter\"} + node_memory_Cached_bytes{job=\"node_exporter\"}+node_memory_Buffers_bytes{job=\"node_exporter\"}))/sum(node_memory_MemTotal_bytes{job=\"node_exporter\"}))",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eno1\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Selectivity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(bolts_emitted / on(TopologyId) group_left() uptime_seconds) / (bolts_executed / on(TopologyId) group_left() uptime_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, bolts_execute_latency[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "bolts_executed / on(TopologyId) group_left() uptime_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "topology_stats_complete_latency{window=\"600\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spouts emitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(quantile_over_time(0.95, rate(spouts_emitted[1m])[2m:1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}