# Generated by Django 4.1.4 on 2023-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0008_rename_master_node_ip_cluster_main_node_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='Cluster',
            name='cluster_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
