# Generated by Django 4.2.16 on 2024-12-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0009_add_cluster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='nodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cluster',
            name='slots',
            field=models.IntegerField(default=0),
        ),
    ]
