# Generated by Django 4.2.16 on 2024-12-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0010_cluster_nodes_cluster_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='hardware_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
